### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by RoRElessar** [olegarutin/library#49]
`Likes` are unfinished

**Comment by olegarutin** [comment]
But I still have time to solve it.

**Comment by RoRElessar** [comment]
But you have submitted the form, so, it means you have done everything

**Comment by olegarutin** [comment]
I'm sorry, i don't know how it happened but I didn't submit the form. I'm still working on my homework

**Comment by RoRElessar** [comment]
A deadline has been ended yesterday.
