### ISSUE TITLE
Lets try 'cookies[:page_visits] = cookies[:page_visits].to_i + 1' instead

### ISSUE THREAD

**Issue by Kashoid23** [olegarutin/library#66]
when `cookies[:page_visits]` is `nil`, `to_i` will convert  it to`0`

https://github.com/olegarutin/library/blob/4c0315c6e6d52c767084e41c647dbae0d38b78d2/app/controllers/posts_controller.rb#L77

**Comment by olegarutin** [comment]
Thanks for your help solving this problem.
